# Generated by Django 2.2.9 on 2020-04-15 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.IntegerField(choices=[(0, 'Electricity'), (1, 'Water')])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DieselStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FoodExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Grains'), (1, 'Gas'), (2, 'Vegetable')])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rto_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stone_type', models.IntegerField(choices=[(0, 'dust'), (6, '6mm'), (10, '10mm'), (20, '20mm'), (30, '30mm')])),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date_of_joining', models.DateTimeField()),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('aadhar_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{12}$')])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.DecimalField(decimal_places=2, max_digits=18, unique=True)),
                ('photo', models.ImageField(default=None, upload_to='')),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SaleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_num', models.IntegerField()),
                ('stone_type', models.IntegerField(choices=[(0, 'dust'), (6, '6mm'), (10, '10mm'), (20, '20mm'), (30, '30mm')])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('desiel_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymanager.CustomerDetail')),
                ('delivery_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymanager.Worker')),
                ('diesel_stock_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moneymanager.DieselStock')),
                ('v_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymanager.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='BlastingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('diesel_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.DieselStock')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymanager.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='AdvPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_given', models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneymanager.Worker')),
            ],
        ),
    ]
