# Generated by Django 2.2.9 on 2020-04-15 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='amt_per_unit',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='bill_num',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='source',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='salelog',
            name='total_amt',
        ),
        migrations.AlterField(
            model_name='salelog',
            name='stone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymanager.StoneType'),
        ),
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_num', models.CharField(max_length=10)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymanager.CustomerDetail')),
            ],
        ),
        migrations.AddField(
            model_name='salelog',
            name='sale_bill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='moneymanager.SaleBill'),
            preserve_default=False,
        ),
    ]
