# Generated by Django 2.1.7 on 2020-04-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanager', '0002_auto_20200415_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='account_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18),
        ),
    ]
